-- =====================================================================
-- CITY HOSPITAL MANAGEMENT SYSTEM - DATABASE SETUP SCRIPT
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. DROP EXISTING TABLES (To prevent "Table already exists" errors)
-- ---------------------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE bill_audit_log CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE bills CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE admissions CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE patients CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE doctors CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE app_users CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP VIEW patient_bill_summary';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 AND SQLCODE != -2449 AND SQLCODE != -4080 THEN
         RAISE;
      END IF;
END;
/

-- ---------------------------------------------------------------------
-- 2. CREATE TABLES (DDL)
-- ---------------------------------------------------------------------

-- App Users Table
CREATE TABLE app_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) NOT NULL
);

-- Patients Table
CREATE TABLE patients (
    patient_id NUMBER PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    dob DATE,
    age NUMBER,
    address VARCHAR2(150),
    phone_number VARCHAR2(20)
);

-- Doctors Table
CREATE TABLE doctors (
    doctor_id NUMBER PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    specialization VARCHAR2(100)
);

-- Admissions Table
CREATE TABLE admissions (
    admission_id NUMBER PRIMARY KEY,
    patient_id NUMBER,
    diagnosis VARCHAR2(200),
    admission_date DATE,
    CONSTRAINT fk_admission_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id)
);

-- Bills Table
CREATE TABLE bills (
    bill_id NUMBER PRIMARY KEY,
    patient_id NUMBER,
    amount NUMBER(10, 2),
    status VARCHAR2(20),
    bill_date DATE,
    CONSTRAINT fk_bill_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id)
);

-- Bill Audit Log Table (For Trigger)
CREATE TABLE bill_audit_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id NUMBER,
    old_status VARCHAR2(20),
    new_status VARCHAR2(20),
    change_date DATE,
    CONSTRAINT fk_audit_bill FOREIGN KEY (bill_id) REFERENCES bills(bill_id)
);

-- ---------------------------------------------------------------------
-- 3. CREATE PL/SQL COMPONENTS (Views & Triggers)
-- ---------------------------------------------------------------------

-- Create View [cite: 337]
CREATE OR REPLACE VIEW patient_bill_summary AS
SELECT p.patient_id, p.first_name, p.last_name, b.bill_id, b.amount, b.status
FROM patients p
JOIN bills b ON p.patient_id = b.patient_id;
/

-- Create BEFORE INSERT Trigger for Age Validation [cite: 341]
CREATE OR REPLACE TRIGGER check_age_trigger
BEFORE INSERT OR UPDATE ON patients
FOR EACH ROW
BEGIN
    IF :NEW.age < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Age cannot be negative!');
    END IF;
END;
/

-- Create AFTER UPDATE Trigger for Audit Logging [cite: 342, 343]
CREATE OR REPLACE TRIGGER log_bill_status
AFTER UPDATE OF status ON bills
FOR EACH ROW
BEGIN
    IF :OLD.status != :NEW.status THEN
        INSERT INTO bill_audit_log (bill_id, old_status, new_status, change_date)
        VALUES (:NEW.bill_id, :OLD.status, :NEW.status, SYSDATE);
    END IF;
END;
/

-- ---------------------------------------------------------------------
-- 4. INSERT DUMMY DATA (DML)
-- ---------------------------------------------------------------------

-- Insert Users
INSERT INTO app_users (username, password, role) VALUES ('admin', 'admin123', 'admin');
INSERT INTO app_users (username, password, role) VALUES ('staff', 'staff123', 'staff');

-- Insert Patients (Explicit IDs to guarantee relationships)
INSERT INTO patients (patient_id, first_name, last_name, dob, age, address, phone_number) 
VALUES (1, 'Alice', 'Smith', TO_DATE('1990-05-15', 'YYYY-MM-DD'), 35, '123 Main St', '555-1111');

INSERT INTO patients (patient_id, first_name, last_name, dob, age, address, phone_number) 
VALUES (2, 'Bob', 'Jones', TO_DATE('1985-10-20', 'YYYY-MM-DD'), 40, '456 Oak Ave', '555-2222');

INSERT INTO patients (patient_id, first_name, last_name, dob, age, address, phone_number) 
VALUES (3, 'Charlie', 'Brown', TO_DATE('2000-01-10', 'YYYY-MM-DD'), 26, '123 Main St', '555-3333');

INSERT INTO patients (patient_id, first_name, last_name, dob, age, address, phone_number) 
VALUES (4, 'Diana', 'Prince', TO_DATE('1975-03-22', 'YYYY-MM-DD'), 50, '789 Pine Rd', '555-4444');

-- Insert Doctors
INSERT INTO doctors (doctor_id, name, specialization) VALUES (1, 'Dr. Adams', 'Cardiology');
INSERT INTO doctors (doctor_id, name, specialization) VALUES (2, 'Dr. Baker', 'Neurology');

-- Insert Admissions
INSERT INTO admissions (admission_id, patient_id, diagnosis, admission_date) 
VALUES (1, 1, 'Arrhythmia', SYSDATE - 12);
    
INSERT INTO admissions (admission_id, patient_id, diagnosis, admission_date) 
VALUES (2, 2, 'Migraine', SYSDATE - 22);

-- Insert Bills
INSERT INTO bills (bill_id, patient_id, amount, status, bill_date) VALUES (1, 1, 1500.00, 'Paid', SYSDATE - 10);
INSERT INTO bills (bill_id, patient_id, amount, status, bill_date) VALUES (2, 1, 500.00, 'Unpaid', SYSDATE - 5);
INSERT INTO bills (bill_id, patient_id, amount, status, bill_date) VALUES (3, 2, 3000.50, 'Paid', SYSDATE - 20);
INSERT INTO bills (bill_id, patient_id, amount, status, bill_date) VALUES (4, 3, 250.00, 'Unpaid', SYSDATE - 2);

-- ---------------------------------------------------------------------
-- 5. SAVE TRANSACTIONS (TCL)
-- ---------------------------------------------------------------------
COMMIT;

PROMPT =======================================================
PROMPT SETUP COMPLETE! All tables, triggers, and data loaded.
PROMPT =======================================================
